use_frameworks!

target 'SJCompmentThreeLib_Example' do
  pod 'SJCompmentThreeLib', :path => '../'

  target 'SJCompmentThreeLib_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
    pod 'FBSnapshotTestCase'
    pod 'Expecta+Snapshots'
  end
end
